# Generated by Django 2.0.7 on 2018-07-21 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NotCompliant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_lot', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('thumb_damage', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('thumb_total', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('area', models.ManyToManyField(to='noconformidad.Area')),
                ('author', models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
                ('cause_select', models.ManyToManyField(to='noconformidad.Cause')),
                ('description_select', models.ManyToManyField(to='noconformidad.Description')),
                ('material_code', models.ManyToManyField(to='noconformidad.Material')),
            ],
        ),
    ]
