# Generated by Django 2.0.7 on 2018-07-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noconformidad', '0002_notcompliant_email_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_cost',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_number',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='material',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
