# Generated by Django 2.0.7 on 2018-07-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noconformidad', '0004_auto_20180721_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoConforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=100)),
                ('email_to', models.CharField(default='', max_length=100)),
                ('area', models.CharField(default='CD04', max_length=100)),
                ('material_quantity', models.IntegerField(default=1)),
                ('thumb_lot', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('thumb_damage', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('thumb_total', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cause',
            name='cause_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='noconforme',
            name='cause_select',
            field=models.ManyToManyField(to='noconformidad.Cause'),
        ),
        migrations.AddField(
            model_name='noconforme',
            name='description_select',
            field=models.ManyToManyField(to='noconformidad.Description'),
        ),
        migrations.AddField(
            model_name='noconforme',
            name='material_code',
            field=models.ManyToManyField(default='', to='noconformidad.Material'),
        ),
    ]
