# Generated by Django 2.0.7 on 2018-07-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noconformidad', '0006_auto_20180721_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noconforme',
            name='description_select',
        ),
        migrations.RemoveField(
            model_name='noconforme',
            name='cause_select',
        ),
        migrations.AddField(
            model_name='noconforme',
            name='cause_select',
            field=models.CharField(default='', max_length=100),
        ),
    ]
